### ISSUE TITLE
an error : Parsingerror: Parenthesizedpattern & only be used one-time

### ISSUE THREAD

**Issue by skyofwing** [SiriusXT/trilium-remember-right-pane#1]
trilium version 0.62.6
I download and import trilium-remember-right-pane.js。Report an error：
![image](https://github.com/SiriusXT/trilium-remember-right-pane/assets/23180952/3fd7cd8d-0a6f-4813-83d2-5a36243fe0b0)
---
When I first started trilium, there were control button. But after I clicked it, the button disappeared. To see it, I can only restart the app.

Toc unfolded when started trilium:
![1](https://github.com/SiriusXT/trilium-remember-right-pane/assets/23180952/286f7d2f-bea6-49a8-a45a-ca2c4d705f3a)

Toc folded when started trilium:
![2](https://github.com/SiriusXT/trilium-remember-right-pane/assets/23180952/a967a98d-9b6c-49d7-8ed0-64e73edc74e2)

**Comment by SiriusXT** [comment]
使用的是最新的脚本吗。
它是点击右侧的叉号按钮，右侧栏会关闭，此刻才会显示打开按钮。
点击打开按钮之后，就这个打开按钮就会消失，因为这个时候右侧面板已经显示了。

再次点击关闭按钮，那个打开按钮就会又显示了

**Comment by skyofwing** [comment]
一开始没有右侧的叉号按钮，我重启了下服务，现在可以了。
感谢分享！
